{"trial_id": "0000", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "num_layers", "default": 1, "conditions": [], "values": [1, 2, 3], "ordered": true}}, {"class_name": "Int", "config": {"name": "dense_units", "default": null, "conditions": [], "min_value": 16, "max_value": 256, "step": 16, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_rate", "default": 0.1, "conditions": [], "min_value": 0.1, "max_value": 0.8, "step": 0.1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.001, 0.0001], "ordered": true}}], "values": {"num_layers": 3, "dense_units": 128, "dropout_rate": 0.5, "learning_rate": 0.01, "tuner/epochs": 2, "tuner/initial_epoch": 0, "tuner/bracket": 2, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 273, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 238, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras_tuner\\src\\tuners\\hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py\", line 53, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.FailedPreconditionError: Graph execution error:\n\nDetected at node 'model/text_vectorization/string_lookup/None_Lookup/LookupTableFindV2' defined at (most recent call last):\n    File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 197, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\traitlets\\config\\application.py\", line 1077, in launch_instance\n      app.start()\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 701, in start\n      self.io_loop.start()\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n      self.asyncio_loop.run_forever()\n    File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\windows_events.py\", line 316, in run_forever\n      super().run_forever()\n    File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n      self._run_once()\n    File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n      handle._run()\n    File \"C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 534, in dispatch_queue\n      await self.process_one()\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 523, in process_one\n      await dispatch(*args)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 429, in dispatch_shell\n      await result\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 767, in execute_request\n      reply_content = await reply_content\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 429, in do_execute\n      res = shell.run_cell(\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2975, in run_cell\n      result = self._run_cell(\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3030, in _run_cell\n      return runner(coro)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n      coro.send(None)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3257, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3473, in run_ast_nodes\n      if (await self.run_code(code, result,  async_=asy)):\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"C:\\Users\\Asus\\AppData\\Local\\Temp\\ipykernel_25400\\677883937.py\", line 13, in <cell line: 13>\n      interactive_context.run(tuner)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\tfx\\orchestration\\experimental\\interactive\\notebook_utils.py\", line 31, in run_if_ipython\n      return fn(*args, **kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\tfx\\orchestration\\experimental\\interactive\\interactive_context.py\", line 164, in run\n      execution_id = launcher.launch().execution_id\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\tfx\\orchestration\\launcher\\base_component_launcher.py\", line 206, in launch\n      self._run_executor(execution_decision.execution_id,\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\tfx\\orchestration\\launcher\\in_process_component_launcher.py\", line 73, in _run_executor\n      executor.Do(\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\tfx\\components\\tuner\\executor.py\", line 122, in Do\n      tuner = search(input_dict, exec_properties, self._get_tmp_dir())\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\tfx\\components\\tuner\\executor.py\", line 106, in search\n      result.search(**tuner_fn_result.fit_kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 233, in search\n      self._try_run_and_update_trial(trial, *fit_args, **fit_kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 273, in _try_run_and_update_trial\n      self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 238, in _run_and_update_trial\n      results = self.run_trial(trial, *fit_args, **fit_kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras_tuner\\src\\tuners\\hyperband.py\", line 427, in run_trial\n      return super().run_trial(trial, *fit_args, **fit_kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n      obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n      results = self.hypermodel.fit(hp, model, *args, **kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n      return model.fit(*args, **kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 1742, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 1338, in train_function\n      return step_function(self, iterator)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 1322, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 1303, in run_step\n      outputs = model.train_step(data)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 1080, in train_step\n      y_pred = self(x, training=True)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 569, in __call__\n      return super().__call__(*args, **kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\engine\\base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\engine\\functional.py\", line 512, in call\n      return self._run_internal_graph(inputs, training=training, mask=mask)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\engine\\functional.py\", line 669, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\engine\\base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\layers\\preprocessing\\text_vectorization.py\", line 632, in call\n      lookup_data = self._lookup_layer(inputs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\engine\\base_layer.py\", line 1150, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 96, in error_handler\n      return fn(*args, **kwargs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\layers\\preprocessing\\index_lookup.py\", line 754, in call\n      lookups = tf.ragged.map_flat_values(self._lookup_dense, inputs)\n    File \"D:\\AI-ML_Project\\machine-learning-operations-mlops\\submissions\\submission-1\\.venv\\lib\\site-packages\\keras\\src\\layers\\preprocessing\\index_lookup.py\", line 792, in _lookup_dense\n      lookups = self.lookup_table.lookup(inputs)\nNode: 'model/text_vectorization/string_lookup/None_Lookup/LookupTableFindV2'\nTable not initialized.\n\t [[{{node model/text_vectorization/string_lookup/None_Lookup/LookupTableFindV2}}]] [Op:__inference_train_function_181663]\n"}